version: '3.8'

services:
  db_booking:
    container_name: ms_booking_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms-booking
    ports:
      - "5495:5432"

  ms-booking:
    container_name: turing_ms_booking
    image: ms-booking:1.0
    ports:
      - "8088:8081"
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
    depends_on:
      - db_booking