version: "3.8"

services:
  postgres:
    container_name: ms_booking_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms-booking
    ports:
      - "5495:5432"
  app:
    build: .
    depends_on:
      - postgres