spring:
  application:
    name: ms-booking
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5495/ms-booking
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yaml
server:
  port: 8088

logging:
  level:
    root: info
