spring:
  application:
    name: ms-booking
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5495/ms-booking
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

#  liquibase:
#    enabled: true
#    change-log: classpath:liquibase/changelog-master.yml
server:
  port: 8088

logging:
  level:
    root: info
#    liquibase: DEBUG
